[file]
[api]
dashboard = true
[entryPoints]
    [entryPoints.http]
    address = ":81"
[backends]
    [backends.backend1]
        [backends.backend1.servers]
            [backends.backend1.servers.server0]
                url = "http://localhost:5001"
                weight = 1
            [backends.backend1.servers.server1]
                url = "http://localhost:5003"
                weight = 2
    [backends.backend2]
        [backends.backend2.servers]
            [backends.backend2.servers.server0]
                url = "http://localhost:5002"
                weight = 1
[frontends]
    [frontends.frontend1]
    backend = "backend1"
        [frontends.frontend1.routes.entry]
        rule = "Path:/first"
    [frontends.frontend2]
    backend = "backend2"
        [frontends.frontend2.routes.entry]
        rule = "Path:/second"
    
